spring:
  application:
    name: news-spring-boot-admin
  jackson:
    time-zone: GMT+8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
server:
  port: 58080

dubbo:
  application:
    id: news-spring-boot-admin
    name: news-spring-boot-admin
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  reference:
    url: dubbo://192.168.100.88:20800

redis:
  host: 192.168.100.100:6379
  port: 6379
  timeout: 1800
